services:
    web:
        image: balance-flow:prod
        build:
            context: .
            target: runner
        environment:
            - NODE_ENV=production
            - PORT=3000
        ports:
            - '3000:3000'
        restart: unless-stopped
